### PR TITLE
Align Pychan with Go's semantic

### PR DESCRIPTION
**Pull request by Kthulhuk**

### CODE REVIEW

**Comment by edouardklein** [comment]
Just a little bit of context:
We need to work on a concurrent programming project, and asyncio's syntax is a PITA to work with, so we decided to port Golang's semantics to Python. We stumbled on pychan a few days ago and we are very happy with what it does.

Our goal is to have as close a match as possible between the Python code and the same code if it was written in Go (with respect to concurrency only).

We summed up the different ways select can be called in test/test_select.go, and wrote a matching select_tests.py.

The latter runs and has its output checked when the tests are run.

Our goal to be as close to Golang's syntax as possible pushes us to rename `quickthread` as `go` and `chanselect` as `select`. If this in unacceptable because of backward compatibility, maybe we can keep both (we will amend the PR if you wish so) ?

We also added a 'default' case to select. We realize a timeout of 0 would have the same effect but we find the  `try catch` is too far from Golang's semantics.

Please do not hesitate to ask us for any clarification.

**Comment by stuglaser** [comment]
Thanks for your contribution Edouard,

It's not a goal for pychan to be word-for-word compatible with go.  `chanselect` is used so it's not confused with `select`, and `quickthread` is used to be more explicit.  Since both of these concepts are less common in Python, I think the longer names make sense here.

If you want to use the same function names as Go, I imagine you already know you can import them like this:

```
from chan import chanselect as select
from chan import quickthread as go
```

I did not quite understand your "default" proposal.  The current implementation is meant to match [Python's Queue](https://docs.python.org/2/library/queue.html#Queue.Queue.put), where the `put` method raises an exception if its timeout triggers.

**Comment by edouardklein** [comment]
No problem on the naming, we'll amend the PR to leave chanselect and quickthread as they are.

As for default, the select statement in Go admits a default clause, which will be executed if and only if no channel is available to read or write. We added it to `chanselect` by way of a named argument which defaults to `False` (and thus does not change the behavior of existing code).

If set to `True`, if and only if there is no channel ready to be written to or read from, chanselect returns 'default', and one can execute a default clause.

We understand that the existing code could make this happen with a timeout of 0, but we find our proposal easier to read:

```
chan, value = chanselect([in1, in2], [], default=True)
if chan == in1:
    pass  #Something with data from in1
elif chan == in2:
    pass  # Something data from in2
elif chan == 'default'
    pass  # Default clause iff in1 and in2 are both not ready
```

vs.

```
chan, value = chanselect([in1, in2], [], timeout=0)
try:
    if chan == in1:
        pass  #Something with data from in1
    elif chan == in2:
        pass  # Something data from in2
except TimeOutError:
    pass  # Default clause iff in1 and in2 are both not ready
```

**Comment by stuglaser** [comment]
Yeah, the API for timeouts is a little awkward, but it is meant to match the API of Queue, so it should be familiar to Python programmers who have used the queue module.

I don't think returning a string sentinel is a common Python idiom.  Are there other mainstream modules that follow this pattern?

**Pull request closed without merging**
